# Generated by Django 4.2 on 2023-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='completed',
        ),
        migrations.AddField(
            model_name='note',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, help_text="None if the note isn't completed. Contain datetime when the note was completed", null=True),
        ),
    ]
