# Generated by Django 4.2 on 2023-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
