# Generated by Django 4.2 on 2023-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_noteuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuser',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
